<#
.SYNOPSIS
Restore full project runtime state from backup.

.DESCRIPTION
Restores PostgreSQL data, MinIO objects, and optionally .env
from a backup folder generated by backup-all.ps1.

.PARAMETER BackupDir
Backup folder path containing public_text.dump and minio_data.zip (or legacy minio_data.tgz).

.PARAMETER DatabaseName
PostgreSQL database name. Default: public_text.

.PARAMETER DatabaseUser
PostgreSQL user. Default: postgres.

.PARAMETER SkipEnvRestore
Skip restoring backup .env to project root.

.PARAMETER Force
Skip interactive confirmation prompt.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$BackupDir,
    [string]$DatabaseName = "public_text",
    [string]$DatabaseUser = "postgres",
    [switch]$SkipEnvRestore,
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Step {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Title,
        [Parameter(Mandatory = $true)]
        [scriptblock]$Action
    )

    Write-Host "`n==> $Title" -ForegroundColor Cyan
    & $Action
}

function Assert-Command {
    param([Parameter(Mandatory = $true)][string]$Name)
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command not found: $Name"
    }
}

function Assert-DockerDaemon {
    & docker info *> $null
    if ($LASTEXITCODE -ne 0) {
        throw @"
Docker daemon is not running.
Please start Docker Desktop and wait until the engine is running, then retry:
  .\restore-all.ps1 -BackupDir <path>
"@
    }
}

function Invoke-DockerCompose {
    param([Parameter(Mandatory = $true)][string[]]$CommandArgs)
    & docker compose @CommandArgs
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose $($CommandArgs -join ' ') failed."
    }
}

function Wait-ForPostgres {
    param(
        [string]$User,
        [int]$Retries = 30,
        [int]$DelaySeconds = 2
    )

    for ($i = 0; $i -lt $Retries; $i++) {
        & docker compose exec -T postgres pg_isready -U $User -d postgres *> $null
        if ($LASTEXITCODE -eq 0) {
            return
        }
        Start-Sleep -Seconds $DelaySeconds
    }

    throw "PostgreSQL is not ready. Please check docker compose logs postgres."
}

function Wait-ForHealth {
    param(
        [string]$Url = "http://localhost:8000/api/health",
        [int]$Retries = 30,
        [int]$DelaySeconds = 2
    )

    for ($i = 0; $i -lt $Retries; $i++) {
        try {
            $resp = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 5
            if ($resp.StatusCode -eq 200) {
                return
            }
        }
        catch {
            # retry
        }
        Start-Sleep -Seconds $DelaySeconds
    }

    throw "Backend health check failed after restore: $Url"
}

$projectRoot = Split-Path -Parent $PSCommandPath
Set-Location $projectRoot

Assert-Command "docker"
Assert-DockerDaemon

if (-not (Test-Path (Join-Path $projectRoot "docker-compose.yml"))) {
    throw "docker-compose.yml not found in $projectRoot"
}

if (-not (Test-Path $BackupDir)) {
    throw "BackupDir not found: $BackupDir"
}

$BackupDir = (Resolve-Path $BackupDir).Path
$dbDumpLocalPath = Join-Path $BackupDir "public_text.dump"
$minioArchiveZipPath = Join-Path $BackupDir "minio_data.zip"
$minioArchiveTgzPath = Join-Path $BackupDir "minio_data.tgz"
$minioArchiveLocalPath = $null
$minioArchiveType = $null
$envBackupPath = Join-Path $BackupDir ".env"
$envTargetPath = Join-Path $projectRoot ".env"
$dbDumpContainerPath = "/tmp/public_text.dump"
$minioExtractRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("public-text-minio-restore-" + [Guid]::NewGuid().ToString("N"))

if (-not (Test-Path $dbDumpLocalPath)) {
    throw "PostgreSQL dump not found: $dbDumpLocalPath"
}
if (Test-Path $minioArchiveZipPath) {
    $minioArchiveLocalPath = $minioArchiveZipPath
    $minioArchiveType = "zip"
}
elseif (Test-Path $minioArchiveTgzPath) {
    $minioArchiveLocalPath = $minioArchiveTgzPath
    $minioArchiveType = "tgz"
}
else {
    throw "MinIO archive not found. Expected one of:`n- $minioArchiveZipPath`n- $minioArchiveTgzPath"
}

if (-not $Force) {
    Write-Host "This operation will overwrite existing PostgreSQL and MinIO data." -ForegroundColor Yellow
    $confirm = Read-Host "Type RESTORE to continue"
    if ($confirm -ne "RESTORE") {
        throw "Restore cancelled."
    }
}

Write-Step -Title "Restore .env file" -Action {
    if ($SkipEnvRestore) {
        Write-Host "Skip .env restore because -SkipEnvRestore was provided."
        return
    }

    if (Test-Path $envBackupPath) {
        Copy-Item $envBackupPath $envTargetPath -Force
        Write-Host "Restored .env to $envTargetPath"
    }
    else {
        Write-Host "No .env found in backup folder, skipped."
    }
}

Write-Step -Title "Ensure postgres and minio are running" -Action {
    Invoke-DockerCompose -CommandArgs @("up", "-d", "postgres", "minio")
}

Write-Step -Title "Wait for postgres ready" -Action {
    Wait-ForPostgres -User $DatabaseUser
}

Write-Step -Title "Ensure target database exists" -Action {
    $sql = "SELECT 1 FROM pg_database WHERE datname = '$DatabaseName';"
    $exists = (& docker compose exec -T postgres psql -U $DatabaseUser -d postgres -tAc $sql)
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to query PostgreSQL databases."
    }

    if ($exists.Trim() -ne "1") {
        & docker compose exec -T postgres psql -U $DatabaseUser -d postgres -c "CREATE DATABASE $DatabaseName;"
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to create database: $DatabaseName"
        }
    }
}

Write-Step -Title "Restore PostgreSQL data" -Action {
    & docker compose cp "$dbDumpLocalPath" "postgres:$dbDumpContainerPath"
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose cp for PostgreSQL dump failed."
    }

    & docker compose exec -T postgres pg_restore -U $DatabaseUser -d $DatabaseName --clean --if-exists --no-owner --no-privileges $dbDumpContainerPath
    if ($LASTEXITCODE -ne 0) {
        throw "pg_restore failed."
    }

    & docker compose exec -T postgres sh -lc "rm -f $dbDumpContainerPath" *> $null
}

Write-Step -Title "Stop app services while restoring object storage" -Action {
    Invoke-DockerCompose -CommandArgs @("stop", "backend", "frontend")
}

Write-Step -Title "Restore MinIO objects" -Action {
    if (Test-Path $minioExtractRoot) {
        Remove-Item -Recurse -Force $minioExtractRoot
    }
    New-Item -ItemType Directory -Force -Path $minioExtractRoot | Out-Null

    if ($minioArchiveType -eq "zip") {
        Expand-Archive -Path $minioArchiveLocalPath -DestinationPath $minioExtractRoot -Force
    }
    else {
        & tar -xzf $minioArchiveLocalPath -C $minioExtractRoot
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to extract legacy archive: $minioArchiveLocalPath"
        }
    }

    $stagingDataPath = Join-Path $minioExtractRoot "__staging_data\data"
    New-Item -ItemType Directory -Force -Path $stagingDataPath | Out-Null

    $sourceDataPath = Join-Path $minioExtractRoot "data"
    if (Test-Path $sourceDataPath) {
        Get-ChildItem -Force -Path $sourceDataPath | Copy-Item -Destination $stagingDataPath -Recurse -Force
    }
    else {
        Get-ChildItem -Force -Path $minioExtractRoot |
            Where-Object { $_.Name -ne "__staging_data" } |
            Copy-Item -Destination $stagingDataPath -Recurse -Force
    }

    & docker compose exec -T minio sh -lc "rm -rf /data/* /data/.[!.]* /data/..?* 2>/dev/null || true"
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to clear MinIO data directory."
    }

    & docker compose cp "$stagingDataPath" "minio:/"
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose cp for MinIO data failed."
    }

    Remove-Item -Recurse -Force $minioExtractRoot
}

Write-Step -Title "Start full stack" -Action {
    Invoke-DockerCompose -CommandArgs @("up", "-d")
}

Write-Step -Title "Verify backend health" -Action {
    Wait-ForHealth
}

Write-Host "`nRestore completed." -ForegroundColor Green
Write-Host "Project URL: http://localhost:5174"
